### ISSUE TITLE
Cross Policy Error

### ISSUE THREAD

**Issue by esersasmaz** [Colouree/Nature4cities-ColoureeAPI#1]
Hi,
APIs work in postman. But I get a cross origin error when I test it on the platform. 

Error Message:
Access to XMLHttpRequest at 'https://app.colouree.com/n4c/api/kpi.json/ugsp/alcala_de_henares/?lon=-3.4&lat=46.7&token=b3190a35-5d44-4981-a74d-be3ad8498f93&assessment=before' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Colouree** [comment]
Hi Eser, 
We checked and there was in fact a problem with the headers.

It is working now.
Thanks.

**Comment by Colouree** [comment]
headers fixed
